### ISSUE TITLE
Relevant Facts - SRS Peer Review Team [34]

### ISSUE THREAD

**Issue by ghost** [wuj187/DigitalTwinCAS#10]
Good work.

“The product can be beneficial for meteorologists to do research” and “The product can be beneficial for forest owners to better manage the forest” are not relevant facts. According to the Volere Template, relevant facts are external factors that influence the product but are not covered by other sections in the requirements template. A relevant fact could be something like high accuracy, usability or the efficiency of using Digital Twin Forest.

**Comment by qasim-ali0** [comment]
@NickCapstone
