### ISSUE TITLE
Assumptions - SRS Peer Review Team [34]

### ISSUE THREAD

**Issue by ghost** [wuj187/DigitalTwinCAS#11]
“The scanning devices are available” and “Virtual Forest should be updated weekly for the first year” are not assumptions but are the givens of using Digital Twin Forest.  An assumption could be that your scanning software is able to model trees from the front and top views of the forest.  

![image](https://user-images.githubusercontent.com/39965649/194780203-7157deca-ae1f-48da-aeb0-5a171c441f3f.png)
from the Volere template.

**Comment by qasim-ali0** [comment]
@NickCapstone
