### ISSUE TITLE
Team6 Review

### ISSUE THREAD

**Issue by michaelilao** [wuj187/DigitalTwinCAS#2]
Review Comments

-In section 1.1 you mentioned this system can help and benefit researchers. Expand on how it can benefit and help them
-In section 1.1 you mentioned this system can help meteorologists and it be beneficial to them. Expand on how it can benefit and help them
-In section 3.1.2 your context diagram shows the modelling team and coding team, are these both your team and is this modelling done by another team.  Expand a bit on roles/responsibilities 
-In your context diagram, you mentioned modelling team, is this a part of your team that will construct the model or another team 3.1.2
-Would have liked to see more NFR’S on Look and Feel to try to visualize what the product might look like? Is it a 3D interface you can tour into or is it more static, hard to get a grasp of how it might/look from the NRF’s and FR’s
-In the FR’s not much mention of how the forest/data will be constructed, consumed or inputted into the system

@CSchank

**Comment by tingyushi** [comment]
Thank you for the review
